### ISSUE TITLE
5.5 式5.192 一行目期待値対象の確率分布

### ISSUE THREAD

**Issue by deasuke** [sammy-suyama/BayesBook#13]
一行目の期待値の中身はdについては1〜DでΣをとっているので、qの中身もdについては1〜Dすべてを考える必要があり、例えばV_{d,m}はV_{・,m}などである必要がある。

**Comment by sammy-suyama** [comment]
ありがとうございます．ご指摘通りの修正で大丈夫だと思います．
かなり終盤の方になってきましたね．．．
