### ISSUE TITLE
3.5節 P.113 事前分布

### ISSUE THREAD

**Issue by henry0312** [sammy-suyama/BayesBook#17]
P.113に誤植があるようです。

式(3.159)直後の「事前分布θ」は「事前分布p(θ)」に、
式(3.160)直前の「事前分布θ」は「事前分布p(θ)」に、

になるのではないかと思いました。

2017年10月20日 第1刷

**Comment by sammy-suyama** [comment]
ご連絡いただきありがとうございます．確認いたしました．
分布なのでp()を付けないとダメですね．
第５刷に向けて修正いたします．
