### ISSUE TITLE
アルゴリズム4.3 q(s_n)の更新 

### ISSUE THREAD

**Issue by deasuke** [sammy-suyama/BayesBook#3]
4.50で必要なη_(n,k)を求めるために、4.51を利用。====> 各期待値 <ln λ_k>,  <λ_k>, <ln π_k>が必要。
====> 4.60〜62を使う。===> a^\hat_k, b^\hat_k, α^\hat_kが必要。 ====> 4.55, 4.58を使う。
====> <s_(n,k)>が必要。====> 4.59を使う。 ====> η_(n,k)が必要。

ということで循環参照しています。当該アルゴリズムの2重ループ内の1ステップのために、さらに収束演算が必要なのでしょうか？そうであれば、アルゴリズム4.3はちょっと端折り過ぎかと。

**Comment by sammy-suyama** [comment]
ご連絡いただきありがとうございます．
基本的には，アルゴリズム4.3の流れ通りでよく，各s_n，λ_k， πに対応する変分パラメータ（ハットがついているもの）を各更新式を使って交互に計算しなおしていけば最適化が進みます．詳しくはソースコードをご参考ください．

**Comment by deasuke** [comment]
ソースコードが正しいとすれば、4.59式は本文にあるように
<s_(n,k)> = η_(n,k)
ではなく、
<s_(n,k)> = s_(n,k)
かと思います。よろしく御願いします。

**Comment by deasuke** [comment]
アルゴリズム4.3の記述と PoissonMixtureModel.jl の記述(別のファイルでしたら該当するファイルを教えて下さい)の乖離が大きく、対応関係を正しく捉えている自信がないので下記、間違っていたら指摘して下さい。

1. function learn_VI (ll.235-252) がアルゴリズム4.3の全体に相当する
2. 本書の4.3ではx_nは1次元のポワソン分布であるからプログラム内でD=1として考えて良い
   (D≧2のときはは「ポワソン分布をD次元に拡張した物」になると思うのですが、どういう分布なんでしょうか？ガンマ分布のパラメータのうちaだけがD倍になっている--bの方はすべての次元で共有される--ので単純にD個のポワソン分布を並べただけでもなさそうですが...)

**Comment by deasuke** [comment]
プログラムではη_(n,k)を求めるためにs_(n,k)を仮のη_(n,k)として、循環参照を1回だけ回した結果をη_(n,k)としているように見えます。本当は何度も回さないと正しいη_(n,k)にはならないが、分布自身にはそこまで影響しない？

**Comment by sammy-suyama** [comment]
１つ１つお答えいたします．
更新式は<s_(n,k)> = η_(n,k)で正しいです．
変分推論の実装では，確率変数sを直接値として持つことはなく，sの分布のパラメータであるηを保持します．
実装上では，expt_s（sの期待値の意味）がηに対応しています．（素直にetaと書いた方がよかったかもしれません）

**Comment by sammy-suyama** [comment]
＞function learn_VI (ll.235-252) がアルゴリズム4.3の全体に相当する
はい，その通りです．基本的なループの流れはその関数です．

＞本書の4.3ではx_nは1次元のポワソン分布であるからプログラム内でD=1として考えて良い
はい，D=1とすれば，本の数式を使った実装と一致するはずです．

＞(D≧2のときはは「ポワソン分布をD次元に拡張した物」になると思うのですが、どういう分布なんでしょうか？
次元間に相関のない多次元観測を扱うモデルになります．2次元でプロットすると「斜め」の相関がないようなモデルです．以前にブログで同じモデルを扱ったのでよろしければご参考ください．（多次元の実装になっているのも以前ブログ用に作ったものを流用したためです．）
http://machine-learning.hatenablog.com/entry/2016/07/06/200605

＞ガンマ分布のパラメータのうちaだけがD倍になっている--bの方はすべての次元で共有される--ので単純にD個のポワソン分布を並べただけでもなさそうですが...)
ブログの方の多次元版をご覧いただければわかるかと思いますが，事前分布の設定でa,bを異なる次元間で同じ値に設定しておくと，bのみ近似事後分布も異なる次元間で同じ値になります．近似事後分布ではbは潜在変数sにのみ依存し，多次元の観測データxには依存しないためです．ブログ中のq(λ)の式では，\hat{b}_d^kと書いてありますが，実際はインデックスdは不要ということになります．

**Comment by sammy-suyama** [comment]
＞プログラムではη_(n,k)を求めるためにs_(n,k)を仮のη_(n,k)として、循環参照を1回だけ回した結果をη_(n,k)としているように見えます。本当は何度も回さないと正しいη_(n,k)にはならないが、分布自身にはそこまで影響しない？

変分パラメータ（η，a，b，α）はまず始めに適当な初期値を与えておき，他の値を固定したうえで残りの値を更新する，というループを繰り返します．
ポアソン混合分布では式（4.46）のように，事後分布を2つの項に近似的に分解することを仮定しています．ここから，
１，ηの更新（E-step）
２，（a,b,α）の更新（M-step）
のような2つのステップが導かれます．したがって，ループとしては上記のE-stepとM-stepを交互に繰り返しているだけになります．
3つ以上に分解した場合は，3ステップになったりします（5章のNMFなど）．

**Comment by deasuke** [comment]
ご回答ありがとうございます。スッキリ理解したと思います!!

> 実装上では，expt_s（sの期待値の意味）がηに対応しています．

それで、関数update_S意味的にはupdate_Etaですね。
あと、add_statsをギブスサンプリングと共通化しているため、引数のSに(GSではsmapleされたSが入るところ)にηが入っている。
たぶんこの辺で混乱していました。

「ηの更新（E-step）」「（a,b,α）の更新（M-step）」という書き方をみてようやく腑に落ちました。
本文のアルゴリズム4.3の記述が、「q(S_n)の更新」「q(λ_k)の更新」「q(π)の更新」の3つが並列な関係に見えていたのが理解を妨げた原因かな、と思いました。

EM両方のステップの繰り返しでもって、私が最初に指摘した「循環参照」で示される方程式を解いている訳ですね。

**Comment by deasuke** [comment]
D≧2の解説もありがとうごさいました。
・b_kはその分布を選らばれた回数だけ増えていく
・ある次元でk番目のポアソン分布が選ばれるときは他のどの次元でもk番目のポアソン分布が選ばれる
したがってb_kの値は次元によらない、ですね。
