### ISSUE TITLE
式3.118

### ISSUE THREAD

**Issue by yurisan** [sammy-suyama/BayesBook#6]
間違っていたら申し訳ないのですが、式3.118のウィシャート分布の第一引数が本では未観測のベクトルx_*となっていますが精度行列Λではないですか？

**Comment by sammy-suyama** [comment]
ご連絡いただきありがとうございます！
ご指摘の通り，Λの確率分布なので第一引数はΛとするべきですね．
大変失礼いたしました．修正いたします．
