### ISSUE TITLE
3.4.3節 観測モデルの式抜け

### ISSUE THREAD

**Issue by deasuke** [sammy-suyama/BayesBook#7]
ここまで読んだ読者なら3.80, 3.96, 3.111から想像付くと思いますが、一応観測モデルの式
p(x | μ, Λ)=N(x | μ, Λ^{-1})
を定義しておいた方が良いと思います。3.131の計算で使っていると思います(自分はこの式(と3.125, 3.128)を3.130に使って3.131の結果を出しました)。

**Comment by sammy-suyama** [comment]
ありがとうございます．確認いたしました．
確かに，平均未知，精度行列未知の場合は観測モデルを書いていましたが，平均・精度未知の場合は観測モデルが明記されていないですね．次の刷で更新できるように検討いたします．
