### ISSUE TITLE
5.1 次元削減VIとサンプルプログラムの対応について

### ISSUE THREAD

**Issue by deasuke** [sammy-suyama/BayesBook#8]
DimensionalityReduction.jlの
71〜73行目と、5.22式
84〜85行目と、5.16式
96, 102〜104行目と、5.27式
が対応していると思うのですが、

X[:,n]は<x_n>,  XX[:,:,n]は<x_n x_n^T>であること、
Σ_wは本文ではすべての次元で共通だが、プログラムでは次元毎に分けていること、
5.28〜5.32の期待値の式、
を考えて、Sigma_W, Sigma_mu, X, XXの更新は理解したのですが、m_W, m_muの更新が理解できません。

m_Wについては73行目にある事前パラメータの項が5.22式の下にはない、
m_uについては+以降の事前パラメータの項が5.16式の下にはないように見えます。
5.28〜5.32の期待値の式を巧く使うとそうなるのかもしれませんが、分かりませんでした。

**Comment by sammy-suyama** [comment]
ご連絡ありがとうございます．
本文では式の導出をなるべく短くするために，式（5.2）および式（5.3）などであえて事前分布の平均パラメータを0に仮定しています．ここにm_W, m_muといった超パラメータを明示的に入れて導出しなおすと，実装のような更新式になります．実装上は，始めから0以外の超パラメータを設計できるようにしておけば，事前分布と（近似）事後分布とで同じクラスが使えるので，逐次学習を行う際などにはとても便利になります．
つまり，数式での解説の簡略性と，実装での利便性で若干異なってしまっているということなのですが，ご指摘いただいた通り，対応関係がはっきりさせた方が良い気がしてきましたので，検討いたします．

**Comment by deasuke** [comment]
> 事前分布の平均パラメータを0に仮定しています．
> ここにm_W, m_muといった超パラメータを明示的に入れて導出しなおすと，実装のような更新式に
なるほど、ありがとうございます。すっきりしました!
